version: '3.7'

services:
  db:
    container_name: postgres-production
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  recruitment_task_api:
    container_name: api-production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5010:80
      - 5011:443
  recruitment_task_calculation:
    container_name: calculation-production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5000:80
      - 5001:443